repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-ast
    - id: detect-private-key
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo:  https://github.com/psf/black
  rev: "22.1.0"
  hooks:
    - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: "4.0.0"
  hooks:
    - id: flake8
- repo: https://github.com/PyCQA/pylint
  rev: pylint-2.6.0
  hooks:
  -   id: pylint
      args:
      - -E
      additional_dependencies:
      - PyMySQL
      - pyyaml
- repo: local
  hooks:
    - id: pytest
      name: Python Tests
      language: system
      entry: python3 -m pytest
      pass_filenames: false
      files: '.py$'
