repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-ast
    - id: check-merge-conflict
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.0
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/PyCQA/pylint
  rev: v3.1.0
  hooks:
  -   id: pylint
      args:
      - --errors-only
      additional_dependencies:
      - PyMySQL
      - pyyaml
      - pytest
      - setuptools
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.16
  hooks:
    - id: validate-pyproject
- repo: local
  hooks:
    - id: pytest
      name: Python Tests
      language: system
      entry: python3 -m pytest
      pass_filenames: false
      files: '.py$'
