name: release

permissions:
  contents: write
  packages: write
  statuses: write
  pull-requests: read

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-pip
          pip3 install build

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get version from git tag
        id: get_version
        uses: battila7/get-version-action@d97fbc34ceb64d1f5d95f4dfd6dce33521ccccf5 # v2.3.0

      - name: Build partition-manager
        run: |
          python3 -m build
          sha256sum dist/*.whl dist/*.tar.gz >dist/sha256sums

      - name: "Publish release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          gh release create "$VERSION" \
            --target "$GITHUB_SHA" \
            --title "partition-manager $VERSION" \
            --generate-notes \
            dist/sha256sums dist/*.whl dist/*.tar.gz
